import "./js/utils/extensions";
import "./js/utils/formatting";
import "./js/database/index";
import "./js/eventhub";
import "./js/machines";
import "./js/player";
import "./js/game";
import "./js/ui/modals";
import "./js/ui/game-ui";