import "./js/database";
import "./js/eventhub";
import "./js/machines/index";
import "./js/towns/index";
import "./js/player";
import "./js/keyboard";
import "./js/game";
import "./js/ui/modals";
import "./js/ui/game-ui";