import "./js/database";
import "./js/eventhub";
import "./js/machines";
import "./js/towns";
import "./js/player";
import "./js/keyboard";
import "./js/game";
import "./js/ui/modals";
import "./js/ui/game-ui";